SAMPLE_CLAIMS = [
    {
        "id": "CLM-2024-001",
        "patient_age": 45,
        "gender": "Male",
        "primary_diagnosis": "E11.9 - Type 2 Diabetes Mellitus without complications",
        "procedures": ["99214 - Office visit, established patient, moderate complexity"],
        "billed_amount": 250.00,
        "provider_type": "Family Medicine",
        "description": "Routine diabetes management visit with A1C review",
    },
    {
        "id": "CLM-2024-002",
        "patient_age": 32,
        "gender": "Female",
        "primary_diagnosis": "J06.9 - Acute Upper Respiratory Infection",
        "procedures": [
            "99213 - Office visit, established patient, low complexity",
            "71046 - Chest X-ray, 2 views",
        ],
        "billed_amount": 680.00,
        "provider_type": "Urgent Care",
        "description": "Common cold symptoms with chest X-ray ordered",
    },
    {
        "id": "CLM-2024-003",
        "patient_age": 58,
        "gender": "Male",
        "primary_diagnosis": "M54.5 - Low Back Pain",
        "procedures": [
            "72148 - MRI Lumbar Spine without contrast",
            "99215 - Office visit, established patient, high complexity",
        ],
        "billed_amount": 3200.00,
        "provider_type": "Orthopedics",
        "description": "First visit for back pain with immediate MRI ordered",
    },
    {
        "id": "CLM-2024-004",
        "patient_age": 70,
        "gender": "Female",
        "primary_diagnosis": "I10 - Essential Hypertension",
        "procedures": [
            "99214 - Office visit, established patient, moderate complexity",
            "93000 - Electrocardiogram (ECG)",
        ],
        "billed_amount": 420.00,
        "provider_type": "Cardiology",
        "description": "Hypertension follow-up with routine ECG monitoring",
    },
    {
        "id": "CLM-2024-005",
        "patient_age": 28,
        "gender": "Male",
        "primary_diagnosis": "S93.401A - Sprain of ankle, initial encounter",
        "procedures": [
            "99283 - Emergency department visit, moderate severity",
            "73610 - X-ray ankle, 3 views",
            "29540 - Strapping of ankle",
            "72148 - MRI Lumbar Spine without contrast",
        ],
        "billed_amount": 4500.00,
        "provider_type": "Emergency Medicine",
        "description": "Ankle sprain in ER with X-ray, strapping, and unrelated lumbar MRI",
    },
]
